// Generated by buildImagePaths.js on 2025-04-24T15:46:15.918Z
window.CARD_SETS = {
  "QuantumContour": {
    "name": "Quantum Contour",
    "types": {
      "dark": {
        "basic": {
          "path": "img/QuantumContour/Dark/P - Dark - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Dark/P - Dark - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Dark/P - Dark - S2.png",
          "isReverse": false
        }
      },
      "dragon": {
        "basic": {
          "path": "img/QuantumContour/Dragon/P - Dragon - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Dragon/P - Dragon - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Dragon/P - Dragon - S2.png",
          "isReverse": false
        }
      },
      "electric": {
        "basic": {
          "path": "img/QuantumContour/Electric/P- Electric - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Electric/P- Electric - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Electric/P- Electric - S2.png",
          "isReverse": false
        }
      },
      "fairy": {
        "basic": {
          "path": "img/QuantumContour/Fairy/P - Fairy - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Fairy/P - Fairy - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Fairy/P - Fairy - S2.png",
          "isReverse": false
        }
      },
      "fighting": {
        "basic": {
          "path": "img/QuantumContour/Fighting/P - Fighting - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Fighting/P - Fighting - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Fighting/P - Fighting - S2.png",
          "isReverse": false
        }
      },
      "fire": {
        "basic": {
          "path": "img/QuantumContour/Fire/P - Fire - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Fire/P - Fire - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Fire/P - Fire - S2.png",
          "isReverse": false
        }
      },
      "grass": {
        "basic": {
          "path": "img/QuantumContour/Grass/P - Grass - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Grass/P- Grass - S1 - R.png",
          "isReverse": true
        },
        "stage-2": {
          "path": "img/QuantumContour/Grass/P- Grass - S2 - R.png",
          "isReverse": true
        }
      },
      "metal": {
        "basic": {
          "path": "img/QuantumContour/Metal/P- Metal - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Metal/P- Metal - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Metal/P- Metal - S2.png",
          "isReverse": false
        }
      },
      "normal": {
        "basic": {
          "path": "img/QuantumContour/Normal/P- Neutral - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Normal/P- Neutral - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Normal/P- Neutral - S2.png",
          "isReverse": false
        }
      },
      "psychic": {
        "basic": {
          "path": "img/QuantumContour/Psychic/P- Psychic - S0.png",
          "isReverse": false
        },
        "stage-1": {
          "path": "img/QuantumContour/Psychic/P- Psychic - S1.png",
          "isReverse": false
        },
        "stage-2": {
          "path": "img/QuantumContour/Psychic/P- Psychic - S2.png",
          "isReverse": false
        }
      },
      "trainers": {},
      "water": {
        "basic": {
          "path": "img/QuantumContour/Water/P- Water - S0 - R.png",
          "isReverse": true
        },
        "stage-1": {
          "path": "img/QuantumContour/Water/P- Water - S1 - R.png",
          "isReverse": true
        },
        "stage-2": {
          "path": "img/QuantumContour/Water/P- Water - S2 - R.png",
          "isReverse": true
        }
      }
    }
  },
  "Classic": {
    "name": "Original Set",
    "types": {
      "water": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "fire": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "grass": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "electric": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "psychic": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "fighting": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "dark": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "metal": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      },
      "normal": {
        "basic": {},
        "stage-1": {},
        "stage-2": {}
      }
    }
  }
};